# Generated by Django 5.2.8 on 2025-12-01 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('council', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('success', 'موفق'), ('failed', 'ناموفق'), ('refunded', 'بازگشت داده شده')], db_index=True, default='pending', max_length=20)),
                ('reference_code', models.CharField(blank=True, db_index=True, help_text='کد رهگیری درگاه پرداخت', max_length=100, null=True, unique=True)),
                ('tracking_code', models.CharField(blank=True, help_text='کد پیگیری بانک - برای نمایش به کاربر', max_length=100, null=True, unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='council.reservation')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'db_table': 'payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reservation'], name='idx_payment_reservation'), models.Index(fields=['status'], name='idx_payment_status'), models.Index(fields=['reference_code'], name='idx_payment_reference')],
            },
        ),
    ]
