# Generated by Django 5.2.8 on 2025-12-11 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(db_index=True, max_length=15, verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('is_otp_verified', models.BooleanField(db_index=True, default=False, verbose_name='تایید شماره با OTP')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='آخرین ورود')),
                ('first_reservation_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ اولین رزرو')),
                ('last_reservation_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ آخرین رزرو')),
                ('total_reservations', models.PositiveIntegerField(default=0, verbose_name='تعداد کل رزروها')),
                ('completed_reservations', models.PositiveIntegerField(default=0, verbose_name='رزروهای تکمیل شده')),
                ('cancelled_reservations', models.PositiveIntegerField(default=0, verbose_name='رزروهای لغو شده')),
                ('pending_reservations', models.PositiveIntegerField(default=0, verbose_name='رزروهای در انتظار')),
                ('total_payments_sum', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مجموع پرداخت\u200cها (تومان)')),
                ('successful_payments_count', models.PositiveIntegerField(default=0, verbose_name='تعداد پرداخت\u200cهای موفق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اطلاعات کاربر',
                'verbose_name_plural': 'اطلاعات کاربران',
                'db_table': 'user_info',
                'ordering': ['-last_reservation_date', '-updated_at'],
                'indexes': [models.Index(fields=['phone'], name='idx_userinfo_phone'), models.Index(fields=['is_otp_verified'], name='idx_userinfo_verified'), models.Index(fields=['last_login'], name='idx_userinfo_login'), models.Index(fields=['total_reservations'], name='idx_userinfo_reservations')],
            },
        ),
    ]
