# Generated by Django 5.2.8 on 2025-12-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_full_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='otp',
            name='idx_otp_phone',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='idx_phone',
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, unique=True, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='is_otp_verified',
            field=models.BooleanField(default=False, verbose_name='تایید شماره با OTP'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='شماره تلفن'),
        ),
    ]
