# Generated by Django 5.2.8 on 2025-12-24 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_otp_code'),
        ('accounts', '0005_remove_otp_idx_otp_phone_remove_user_idx_phone_and_more'),
    ]

    operations = [
    ]
