# Generated by Django 5.2.8 on 2025-12-14 15:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام توصیفی برای این قالب', max_length=100, verbose_name='نام قالب')),
                ('description', models.TextField(blank=True, help_text='توضیح کامل درباره این قالب و کاربردش', verbose_name='توضیحات')),
                ('template_json', models.JSONField(default=dict, help_text='ساختار JSON شامل موقعیت\u200cها و تنظیمات بخش\u200cها', verbose_name='تنظیمات قالب')),
                ('thumbnail', models.ImageField(blank=True, help_text='تصویر پیش\u200cنمایش قالب', null=True, upload_to='layouts/thumbnails/', verbose_name='تصویر نمونه')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='قالب\u200cهای غیرفعال در لیست نمایش داده نمی\u200cشوند', verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'قالب',
                'verbose_name_plural': 'قالب\u200cها',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان پست بلاگ (حداکثر 255 کاراکتر)', max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(help_text='URL خودکار از عنوان ساخته می\u200cشود', max_length=255, unique=True, verbose_name='اسلاگ')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده'), ('archived', 'بایگانی شده')], db_index=True, default='draft', help_text='وضعیت انتشار پست', max_length=20, verbose_name='وضعیت')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='زمان انتشار پست (اگر منتشر شده باشد)', null=True, verbose_name='تاریخ انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('meta_description', models.TextField(blank=True, help_text='توضیحات برای SEO (حداکثر 160 کاراکتر)', max_length=160, verbose_name='توضیحات متا')),
                ('featured_image', models.ImageField(blank=True, help_text='تصویر اصلی پست که در لیست و صفحه پست نمایش داده می\u200cشود', null=True, upload_to='posts/featured/%Y/%m/%d/', verbose_name='تصویر شاخص')),
                ('author', models.ForeignKey(help_text='ادمینی که این پست را نوشته است', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست\u200cها',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('text', 'متن'), ('image', 'تصویر'), ('gallery', 'گالری تصاویر'), ('quote', 'نقل قول'), ('code', 'کد'), ('video', 'ویدیو')], db_index=True, help_text='نوع محتوای این بخش', max_length=20, verbose_name='نوع بخش')),
                ('content', models.TextField(help_text='محتوای متنی', verbose_name='محتوا')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='ترتیب نمایش این بخش (عدد کوچکتر = بالاتر)', verbose_name='ترتیب')),
                ('position_choice', models.CharField(choices=[('top-left', 'بالا - چپ'), ('top-center', 'بالا - وسط'), ('top-right', 'بالا - راست'), ('middle-left', 'وسط - چپ'), ('middle-center', 'وسط - وسط'), ('middle-right', 'وسط - راست'), ('bottom-left', 'پایین - چپ'), ('bottom-center', 'پایین - وسط'), ('bottom-right', 'پایین - راست'), ('custom', 'سفارشی')], default='top-center', help_text='موقعیت از پیش تعریف شده - اگر "سفارشی" انتخاب شود، position_x و position_y استفاده می\u200cشود', max_length=20, verbose_name='موقعیت')),
                ('position_x', models.CharField(blank=True, help_text='موقعیت X سفارشی (مثلا: 10%, 50px, 2rem) - فقط برای موقعیت سفارشی', max_length=20, null=True, verbose_name='موقعیت افقی')),
                ('position_y', models.CharField(blank=True, help_text='موقعیت Y سفارشی (مثلا: 20%, 100px, 5rem) - فقط برای موقعیت سفارشی', max_length=20, null=True, verbose_name='موقعیت عمودی')),
                ('width', models.CharField(default='100%', help_text='عرض بخش (مثلا: 100%, 500px, auto)', max_length=20, verbose_name='عرض')),
                ('height', models.CharField(default='auto', help_text='ارتفاع بخش (مثلا: auto, 300px, 50vh)', max_length=20, verbose_name='ارتفاع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('post', models.ForeignKey(help_text='پستی که این بخش به آن تعلق دارد', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='blog.post', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'بخش پست',
                'verbose_name_plural': 'بخش\u200cهای پست',
                'ordering': ['post', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='فایل رسانه\u200cای (عکس، ویدیو، صوت)', upload_to='posts/media/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'mp4', 'webm', 'mp3', 'wav'])], verbose_name='فایل')),
                ('file_type', models.CharField(choices=[('image', 'تصویر'), ('video', 'ویدیو'), ('audio', 'صوت')], db_index=True, help_text='نوع فایل برای نمایش صحیح', max_length=10, verbose_name='نوع فایل')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='حجم فایل به بایت - برای مدیریت فضای ذخیره\u200cسازی', null=True, verbose_name='حجم فایل')),
                ('alt_text', models.CharField(blank=True, help_text='توضیح تصویر برای SEO و دسترسی\u200cپذیری', max_length=255, verbose_name='متن جایگزین')),
                ('caption', models.TextField(blank=True, help_text='کپشن برای نمایش زیر تصویر', verbose_name='کپشن')),
                ('width', models.PositiveIntegerField(blank=True, help_text='عرض تصویر/ویدیو به پیکسل', null=True, verbose_name='عرض')),
                ('height', models.PositiveIntegerField(blank=True, help_text='ارتفاع تصویر/ویدیو به پیکسل', null=True, verbose_name='ارتفاع')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ آپلود')),
                ('post', models.ForeignKey(help_text='پستی که این فایل به آن تعلق دارد', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='blog.post', verbose_name='پست')),
                ('section', models.ForeignKey(blank=True, help_text='بخش خاصی که این فایل در آن استفاده شده (اختیاری)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='blog.postsection', verbose_name='بخش')),
            ],
            options={
                'verbose_name': 'فایل رسانه\u200cای',
                'verbose_name_plural': 'فایل\u200cهای رسانه\u200cای',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', '-published_at'], name='post_status_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-created_at'], name='post_author_date_idx'),
        ),
        migrations.AddIndex(
            model_name='postsection',
            index=models.Index(fields=['post', 'order'], name='section_post_order_idx'),
        ),
        migrations.AddIndex(
            model_name='postsection',
            index=models.Index(fields=['post', 'section_type'], name='section_post_type_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['post', 'file_type'], name='media_post_type_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['post', '-created_at'], name='media_post_date_idx'),
        ),
    ]
