# Generated by Django 5.2.8 on 2025-12-15 11:30

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='template_json',
            field=models.JSONField(default=blog.models.get_default_layout_json, help_text='ساختار JSON شامل موقعیت\u200cها و تنظیمات بخش\u200cها', verbose_name='تنظیمات قالب'),
        ),
    ]
