# Generated by Django 5.2.8 on 2025-12-16 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_layout_template_json'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام نویسنده', max_length=100, verbose_name='نام')),
                ('avatar', models.ImageField(blank=True, help_text='تصویر پروفایل نویسنده', null=True, upload_to='authors/avatars/', verbose_name='آواتار')),
                ('bio', models.TextField(blank=True, help_text='معرفی کوتاه نویسنده', verbose_name='بیوگرافی')),
                ('linkedin', models.URLField(blank=True, help_text='آدرس لینکدین', verbose_name='لینکدین')),
                ('twitter', models.URLField(blank=True, help_text='آدرس توییتر', verbose_name='توییتر')),
                ('instagram', models.URLField(blank=True, help_text='آدرس اینستاگرام', verbose_name='اینستاگرام')),
                ('website', models.URLField(blank=True, help_text='وبسایت شخصی', verbose_name='وبسایت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسندگان',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='post_author_date_idx',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='editor',
            field=models.ForeignKey(default=1, help_text='ادمینی که این پست را تنظیم کرده است', on_delete=django.db.models.deletion.CASCADE, related_name='edited_posts', to=settings.AUTH_USER_MODEL, verbose_name='ویرایشگر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='authors',
            field=models.ManyToManyField(blank=True, help_text='نویسندگان این پست', related_name='posts', to='blog.author', verbose_name='نویسندگان'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['editor', '-created_at'], name='post_editor_date_idx'),
        ),
    ]
