# Generated by Django 5.2.8 on 2025-12-16 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_author_remove_post_post_author_date_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='آدرس IP کاربری که لایک کرده', verbose_name='آی\u200cپی کاربر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ لایک')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.post', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'لایک',
                'verbose_name_plural': 'لایک\u200cها',
                'indexes': [models.Index(fields=['post', 'ip_address'], name='like_post_ip_idx')],
                'unique_together': {('post', 'ip_address')},
            },
        ),
    ]
