# Generated by Django 5.2.8 on 2025-12-21 09:51

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postlike'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='تگ های مرتبط با پست را ثبت کنید', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='تگ ها'),
        ),
    ]
