# Generated by Django 5.2.8 on 2025-12-21 14:47

import django.db.models.deletion
import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_tags'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='تگ های مرتبط با پست را ثبت کنید', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='تگ ها'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='نام کامل (اختیاری - برای کامنت ناشناس خالی بگذارید)', max_length=100, verbose_name='نام')),
                ('email', models.EmailField(blank=True, help_text='آدرس ایمیل (اختیاری)', max_length=254, verbose_name='ایمیل')),
                ('anonymous_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='شناسه یکتا برای کاربران ناشناس', verbose_name='شناسه ناشناس')),
                ('content', models.TextField(help_text='محتوای نظر', verbose_name='متن نظر')),
                ('ip_address', models.GenericIPAddressField(help_text='آدرس IP برای مدیریت', verbose_name='آی\u200cپی')),
                ('is_approved', models.BooleanField(db_index=True, default=False, help_text='آیا این نظر توسط ادمین تایید شده است؟', verbose_name='تایید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('parent', models.ForeignKey(blank=True, help_text='کامنت والد (برای پاسخ\u200cها)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment', verbose_name='والد')),
                ('post', models.ForeignKey(help_text='پستی که این کامنت به آن تعلق دارد', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post', 'is_approved', '-created_at'], name='comment_post_approved_idx'), models.Index(fields=['parent', '-created_at'], name='comment_parent_idx')],
            },
        ),
    ]
