# Generated by Django 5.2.8 on 2025-12-21 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_tags_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='anonymous_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_admin_reply',
            field=models.BooleanField(db_index=True, default=False, help_text='آیا این پاسخ توسط ادمین ثبت شده است؟', verbose_name='پاسخ ادمین'),
        ),
        migrations.AddField(
            model_name='comment',
            name='replied_by',
            field=models.ForeignKey(blank=True, help_text='ادمینی که این پاسخ را ثبت کرده (فقط برای پاسخ\u200cهای ادمین)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_comment_replies', to=settings.AUTH_USER_MODEL, verbose_name='پاسخ داده شده توسط'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['is_admin_reply'], name='comment_admin_reply_idx'),
        ),
    ]
