# Generated by Django 5.2.8 on 2025-12-21 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_comment_anonymous_id_comment_is_admin_reply_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='comment_admin_reply_idx',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_admin_reply',
        ),
        migrations.AddField(
            model_name='comment',
            name='admin_replied_at',
            field=models.DateTimeField(blank=True, help_text='زمانی که ادمین پاسخ داده', null=True, verbose_name='زمان پاسخ ادمین'),
        ),
        migrations.AddField(
            model_name='comment',
            name='admin_reply',
            field=models.TextField(blank=True, help_text='پاسخ مستقیم ادمین به این کامنت', verbose_name='پاسخ ادمین'),
        ),
        migrations.AddField(
            model_name='comment',
            name='answered_by_admin',
            field=models.BooleanField(db_index=True, default=False, help_text='آیا ادمین به این کامنت پاسخ داده است؟', verbose_name='پاسخ داده شده توسط ادمین'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='replied_by',
            field=models.ForeignKey(blank=True, help_text='ادمینی که به این کامنت پاسخ داده', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_comment_replies', to=settings.AUTH_USER_MODEL, verbose_name='پاسخ داده شده توسط'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['answered_by_admin'], name='comment_answered_idx'),
        ),
    ]
