# Generated by Django 5.2.8 on 2025-12-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_comment_comment_admin_reply_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='answered_by_admin',
            field=models.BooleanField(default=False, help_text='آیا ادمین به این کامنت پاسخ داده است؟', verbose_name='پاسخ داده شده توسط ادمین'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='آیا این نظر توسط ادمین تایید شده است؟', verbose_name='تایید شده'),
        ),
    ]
