# Generated by Django 5.2.8 on 2025-12-23 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comment_answered_by_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommenterIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True, verbose_name='IP')),
                ('is_blocked', models.BooleanField(db_index=True, default=False, verbose_name='بلاک شده؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='اولین بار دیده شد')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بار دیده شد')),
            ],
            options={
                'verbose_name': 'IP کامنت\u200cگذار',
                'verbose_name_plural': 'IPهای کامنت\u200cگذار',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='commenter_ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='blog.commenterip', verbose_name='IP مرجع'),
        ),
    ]
