# Generated by Django 5.2.8 on 2025-11-30 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('reservation', 'گزارش رزرو'), ('user', 'گزارش کاربر'), ('payment', 'گزارش پرداخت'), ('system', 'گزارش سیستم')], db_index=True, max_length=20)),
                ('related_id', models.PositiveIntegerField(blank=True, help_text='ID مرتبط با نوع گزارش', null=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_visible_to_user', models.BooleanField(default=False, help_text='آیا کاربر می\u200cتواند این گزارش را ببیند؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'گزارش',
                'verbose_name_plural': 'گزارش\u200cها',
                'db_table': 'reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type'], name='idx_report_type'), models.Index(fields=['type', 'related_id'], name='idx_report_relation'), models.Index(fields=['created_by'], name='idx_report_creator')],
            },
        ),
    ]
