# Generated by Django 5.2.8 on 2025-12-01 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('reservation', 'گزارش رزرو'), ('user', 'گزارش کاربر'), ('payment', 'گزارش پرداخت'), ('system', 'گزارش سیستم')], db_index=True, help_text='نوع موجودیتی که گزارش درباره آن است', max_length=20, verbose_name='نوع گزارش')),
                ('related_id', models.PositiveIntegerField(blank=True, help_text='شناسه رکورد مرتبط (مثلاً ID رزرو یا کاربر)', null=True, verbose_name='شناسه مرتبط')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان گزارش')),
                ('content', models.TextField(help_text='متن کامل گزارش', verbose_name='محتوای گزارش')),
                ('is_visible_to_user', models.BooleanField(default=False, help_text='آیا کاربر می\u200cتواند این گزارش را مشاهده کند؟', verbose_name='قابل مشاهده برای کاربر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('created_by', models.ForeignKey(help_text='کاربری که این گزارش را ایجاد کرده است', on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
            ],
            options={
                'verbose_name': 'گزارش',
                'verbose_name_plural': 'گزارش\u200cها',
                'db_table': 'reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type'], name='idx_report_type'), models.Index(fields=['type', 'related_id'], name='idx_report_relation'), models.Index(fields=['created_by'], name='idx_report_creator'), models.Index(fields=['is_visible_to_user'], name='idx_report_visibility')],
            },
        ),
    ]
