# Generated by Django 5.2.3 on 2025-10-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneticConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تلفن')),
                ('prescription_file', models.FileField(blank=True, null=True, upload_to='consultation_prescriptions/', verbose_name='آپلود نسخه/مدارک')),
                ('service_type', models.CharField(max_length=100, verbose_name='نوع خدمت درخواستی')),
                ('message', models.TextField(verbose_name='پیام یا توضیحات تکمیلی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'درخواست مشاوره ژنتیک',
                'verbose_name_plural': 'درخواست\u200cهای مشاوره ژنتیک',
            },
        ),
    ]
