# Generated by Django 5.2.8 on 2025-12-01 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import council.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام خدمت')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='شناسه URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت (تومان)')),
                ('duration', models.PositiveIntegerField(help_text='مدت زمان مشاوره به دقیقه', verbose_name='مدت زمان (دقیقه)')),
                ('is_online', models.BooleanField(default=True, help_text='آیا این خدمت به صورت غیرحضوری ارائه می\u200cشود؟', verbose_name='غیرحضوری')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, help_text='ترتیب نمایش در لیست', verbose_name='ترتیب نمایش')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'نوع خدمت',
                'verbose_name_plural': 'انواع خدمات',
                'db_table': 'service_types',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='idx_service_slug'), models.Index(fields=['is_active'], name='idx_service_active')],
            },
        ),
        migrations.CreateModel(
            name='SlotRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: برنامه حضوری پاییز 1403', max_length=100, verbose_name='نام الگو')),
                ('weekdays', models.CharField(help_text='روزهای هفته با کاما جدا شده: 0,1,2,3,4', max_length=20, verbose_name='روزهای هفته')),
                ('start_time', models.TimeField(verbose_name='زمان شروع')),
                ('end_time', models.TimeField(verbose_name='زمان پایان')),
                ('slot_duration', models.PositiveIntegerField(default=60, help_text='مدت زمان هر نوبت به دقیقه', verbose_name='مدت هر نوبت (دقیقه)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('apply_from_date', models.DateField(blank=True, help_text='از چه تاریخی این الگو اعمال شود (اختیاری)', null=True, verbose_name='تاریخ شروع اعمال')),
                ('apply_to_date', models.DateField(blank=True, help_text='تا چه تاریخی این الگو اعمال شود (اختیاری)', null=True, verbose_name='تاریخ پایان اعمال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_rules', to='council.servicetype', verbose_name='نوع خدمت')),
            ],
            options={
                'verbose_name': 'قانون بازه زمانی',
                'verbose_name_plural': 'قوانین بازه\u200cهای زمانی',
                'db_table': 'slot_rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='تاریخ')),
                ('start_time', models.TimeField(verbose_name='زمان شروع')),
                ('end_time', models.TimeField(verbose_name='زمان پایان')),
                ('is_available', models.BooleanField(db_index=True, default=True, help_text='آیا این نوبت قابل رزرو است؟', verbose_name='در دسترس')),
                ('is_manual', models.BooleanField(default=False, help_text='آیا این نوبت به صورت دستی ایجاد شده است؟', verbose_name='ایجاد دستی')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_slots', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('created_from_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_slots', to='council.slotrule', verbose_name='ایجاد شده از الگو')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='council.servicetype', verbose_name='نوع خدمت')),
            ],
            options={
                'verbose_name': 'بازه زمانی',
                'verbose_name_plural': 'بازه\u200cهای زمانی',
                'db_table': 'time_slots',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(db_index=True, help_text='کد یکتای رزرو برای پیگیری', max_length=20, unique=True, verbose_name='کد پیگیری')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('phone_number', models.CharField(db_index=True, max_length=15, verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید شماره'), ('phone_verified', 'شماره تایید شده - در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('completed', 'انجام شده'), ('cancelled', 'لغو شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('payment_status', models.CharField(choices=[('unpaid', 'پرداخت نشده'), ('paid', 'پرداخت شده'), ('refunded', 'بازگشت داده شده')], default='unpaid', max_length=20, verbose_name='وضعیت پرداخت')),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید شماره')),
                ('message', models.TextField(blank=True, help_text='یادداشت یا توضیحات کاربر', null=True, verbose_name='پیام و توضیحات')),
                ('prescription', models.FileField(blank=True, help_text='فایل نسخه (در صورت نیاز)', null=True, upload_to=council.models.prescription_upload_path, verbose_name='نسخه پزشک')),
                ('reserved_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان رزرو')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.ForeignKey(blank=True, help_text='پس از تایید OTP، کاربر مرتبط می\u200cشود', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='council.servicetype', verbose_name='نوع خدمت')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='council.timeslot', verbose_name='بازه زمانی')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزروها',
                'db_table': 'reservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['date'], name='idx_slot_date'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['date', 'start_time'], name='idx_time_lookup'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['date', 'is_available'], name='idx_available_slots'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['service_type'], name='idx_slot_service'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('service_type', 'date', 'start_time'), name='unique_service_datetime'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['user'], name='idx_reservation_user'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status'], name='idx_reservation_status'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['tracking_code'], name='idx_tracking_code'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['phone_number'], name='idx_reservation_phone'),
        ),
    ]
