# Generated by Django 5.2.8 on 2025-12-04 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: مشاوره تغذیه، مشاوره ورزشی', max_length=200, unique=True, verbose_name='عنوان موضوع')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='شناسه URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'موضوع مشاوره',
                'verbose_name_plural': 'موضوعات مشاوره',
                'db_table': 'consultation_topics',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'ordering': ['order', 'name'], 'verbose_name': 'نوع سرویس', 'verbose_name_plural': 'انواع سرویس ها'},
        ),
        migrations.AlterModelOptions(
            name='slotrule',
            options={'ordering': ['-created_at'], 'verbose_name': 'الگو بازه زمانی', 'verbose_name_plural': 'الگو های بازه\u200cهای زمانی'},
        ),
        migrations.AddField(
            model_name='timeslot',
            name='is_expired',
            field=models.BooleanField(db_index=True, default=False, help_text='آیا زمان این نوبت گذشته است؟', verbose_name='منقضی شده'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='council.servicetype', verbose_name='نوع مشاوره'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='is_online',
            field=models.BooleanField(default=True, help_text='آیا این سرویس به صورت غیرحضوری ارائه می\u200cشود؟', verbose_name='غیرحضوری'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(help_text='یک نام برای نوع مشاوره یا سرویس ارائه کنید', max_length=100, unique=True, verbose_name='نام سرویس'),
        ),
        migrations.AlterField(
            model_name='slotrule',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_rules', to='council.servicetype', verbose_name='نوع مشاوره'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='council.servicetype', verbose_name='نوع مشاوره'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['is_expired'], name='idx_slot_expired'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='consultation_topic',
            field=models.ForeignKey(blank=True, help_text='موضوع اصلی مشاوره', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='council.consultationtopic', verbose_name='عنوان مشاوره'),
        ),
    ]
