# Generated by Django 5.2.8 on 2025-11-25 09:21

import council.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneticconsultationrequest',
            name='prescription_file',
            field=models.FileField(blank=True, null=True, upload_to='consultation_prescriptions/', validators=[council.models.validate_file_size], verbose_name='آپلود نسخه/مدارک'),
        ),
    ]
