# Generated by Django 5.2.8 on 2025-11-25 10:24

import council.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0002_alter_geneticconsultationrequest_prescription_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geneticconsultationrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'درخواست مشاوره ژنتیک', 'verbose_name_plural': 'درخواست\u200cهای مشاوره ژنتیک'},
        ),
        migrations.AlterField(
            model_name='geneticconsultationrequest',
            name='prescription_file',
            field=models.FileField(blank=True, null=True, upload_to='consultation_prescriptions/', validators=[council.models.validate_file_size, council.models.validate_file_extension], verbose_name='آپلود نسخه/مدارک'),
        ),
    ]
