# Generated by Django 5.2.8 on 2025-12-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0002_consultationtopic_alter_servicetype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='در صورت فعال بودن، این تنظیمات به عنوان تنظیمات اصلی سیستم استفاده می\u200cشود.', verbose_name='فعال')),
                ('payment_deadline_minutes', models.PositiveIntegerField(default=60, help_text='مهلت پرداخت پس از تأیید شماره تلفن (به دقیقه).', verbose_name='مهلت پرداخت (دقیقه)')),
                ('min_reservable_day', models.PositiveIntegerField(default=1, help_text='کاربر حداقل چند روز قبل از نوبت می\u200cتواند رزرو ها را مشاهده کند؟', verbose_name='حداقل روزهای قابل رزرو')),
                ('max_reservable_day', models.PositiveIntegerField(default=30, help_text='کاربر حداکثر چند روز آینده را می\u200cتواند رزرو کند؟', verbose_name='حداکثر روزهای قابل رزرو')),
                ('expiration_slot_day', models.PositiveIntegerField(default=1, help_text='چند روز قبل از زمان نوبت باید آن را منقضی و غیرقابل رزرو کرد؟', verbose_name='روز منقضی شدن نوبت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات رزرو',
                'verbose_name_plural': 'تنظیمات رزرو',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='consultationtopic',
            name='name',
            field=models.CharField(help_text='مثال: مشاوره تغذیه، مشاوره ورزشی', max_length=200, unique=True, verbose_name='عنوان'),
        ),
    ]
