# Generated by Django 5.2.8 on 2025-12-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0003_reservationsettings_alter_consultationtopic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationsettings',
            name='expiration_deadline_minutes',
            field=models.PositiveIntegerField(default=60, help_text='مدت زمانی که اگر کاربر پرداخت را انجام ندهد، نوبت به صورت خودکار منقضی می\u200cشود.', verbose_name='مهلت منقضی شدن نوبت (دقیقه)'),
        ),
        migrations.AlterField(
            model_name='reservationsettings',
            name='payment_deadline_minutes',
            field=models.PositiveIntegerField(default=15, help_text='مهلت پرداخت پس از تأیید شماره تلفن (به دقیقه).', verbose_name='مهلت پرداخت (دقیقه)'),
        ),
    ]
