# Generated by Django 5.2.8 on 2025-11-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0003_alter_geneticconsultationrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneticconsultationrequest',
            name='service_type',
            field=models.CharField(choices=[('', 'انتخاب خدمت'), ('سرطان', 'آزمایشگاه سرطان'), ('مادر_جنین', 'آزمایشگاه سلامت مادر و جنین'), ('مولکولی', 'ژنتیک مولکولی'), ('سایر', 'سایر خدمات')], default='', max_length=100, verbose_name='نوع خدمت درخواستی'),
        ),
    ]
