# Generated by Django 5.2.8 on 2025-11-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0004_alter_geneticconsultationrequest_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='geneticconsultationrequest',
            name='is_reviewed',
            field=models.BooleanField(default=False, verbose_name='بررسی شد'),
        ),
    ]
