# Generated by Django 5.2.8 on 2025-12-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0004_reservationsettings_expiration_deadline_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='full_name',
            field=models.CharField(max_length=50, verbose_name='نام و نام خانوادگی'),
        ),
    ]
