# Generated by Django 5.2.8 on 2025-11-25 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0005_geneticconsultationrequest_is_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geneticconsultationrequest',
            name='is_reviewed',
        ),
    ]
