# Generated by Django 5.2.8 on 2025-12-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0005_alter_reservation_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='sepas_code',
            field=models.CharField(blank=True, help_text='کد سامانه سپاس را وارد کنید', max_length=100, null=True, verbose_name='کد سپاس'),
        ),
    ]
