# Generated by Django 5.2.8 on 2025-12-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0006_reservation_sepas_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='sepas_code',
            field=models.CharField(blank=True, help_text='کد سامانه سپاس را وارد کنید', max_length=50, null=True, verbose_name='کد سپاس'),
        ),
    ]
