# Generated by Django 5.2.8 on 2025-12-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0007_alter_reservation_sepas_code'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reservation',
            name='idx_reservation_user',
        ),
        migrations.RemoveIndex(
            model_name='reservation',
            name='idx_tracking_code',
        ),
        migrations.RemoveIndex(
            model_name='servicetype',
            name='idx_service_slug',
        ),
        migrations.RemoveIndex(
            model_name='timeslot',
            name='idx_slot_service',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید شماره'), ('phone_verified', 'شماره تایید شده - در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('completed', 'انجام شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='tracking_code',
            field=models.CharField(help_text='کد یکتای رزرو برای پیگیری', max_length=20, unique=True, verbose_name='کد پیگیری'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='date',
            field=models.DateField(verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='is_available',
            field=models.BooleanField(default=True, help_text='آیا این نوبت قابل رزرو است؟', verbose_name='در دسترس'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='is_expired',
            field=models.BooleanField(default=False, help_text='آیا زمان این نوبت گذشته است؟', verbose_name='منقضی شده'),
        ),
    ]
