# Generated by Django 5.2.8 on 2025-12-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0008_remove_reservation_idx_reservation_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='counselor_gender',
            field=models.CharField(choices=[('no_preference', 'مهم نیست'), ('male', 'مرد'), ('female', 'زن')], default='no_preference', max_length=20, verbose_name='جنسیت مشاور'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='sepas_code',
            field=models.CharField(blank=True, help_text='کد ملی را وارد کنید', max_length=50, null=True, verbose_name='کد ملی'),
        ),
    ]
