# Generated by Django 5.2.7 on 2025-12-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0009_reservation_counselor_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='counselor_gender',
            field=models.CharField(choices=[('no_preference', 'هر کدام'), ('male', 'مرد'), ('female', 'زن')], default='no_preference', max_length=20, verbose_name='جنسیت مشاور'),
        ),
    ]
