# Generated by Django 5.2.8 on 2025-12-08 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_email'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('council', '0002_consultationtopic_alter_servicetype_options_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='statistics', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('total_reservations', models.PositiveIntegerField(default=0, verbose_name='مجموع رزروها')),
                ('completed_reservations', models.PositiveIntegerField(default=0, verbose_name='رزروهای تکمیل شده')),
                ('cancelled_reservations', models.PositiveIntegerField(default=0, verbose_name='رزروهای لغو شده')),
                ('pending_reservations', models.PositiveIntegerField(default=0, verbose_name='رزروهای در انتظار')),
                ('total_payments', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مجموع پرداخت\u200cها')),
                ('successful_payments', models.PositiveIntegerField(default=0, verbose_name='پرداخت\u200cهای موفق')),
                ('failed_payments', models.PositiveIntegerField(default=0, verbose_name='پرداخت\u200cهای ناموفق')),
                ('refunded_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ بازگشتی')),
                ('total_logins', models.PositiveIntegerField(default=0, verbose_name='تعداد ورود')),
                ('total_activities', models.PositiveIntegerField(default=0, verbose_name='تعداد فعالیت\u200cها')),
                ('first_activity', models.DateTimeField(blank=True, null=True, verbose_name='اولین فعالیت')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='آخرین فعالیت')),
                ('last_reservation', models.DateTimeField(blank=True, null=True, verbose_name='آخرین رزرو')),
                ('last_payment', models.DateTimeField(blank=True, null=True, verbose_name='آخرین پرداخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('most_used_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='council.servicetype', verbose_name='خدمت پرکاربرد')),
            ],
            options={
                'verbose_name': 'آمار کاربر',
                'verbose_name_plural': 'آمار کاربران',
                'db_table': 'user_statistics',
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('validation', 'خطای اعتبارسنجی'), ('database', 'خطای دیتابیس'), ('payment', 'خطای پرداخت'), ('api', 'خطای API'), ('server', 'خطای سرور'), ('other', 'سایر')], db_index=True, max_length=30, verbose_name='نوع خطا')),
                ('error_message', models.TextField(verbose_name='پیام خطا')),
                ('stack_trace', models.TextField(blank=True, null=True, verbose_name='Stack Trace')),
                ('url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL')),
                ('view_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام View')),
                ('request_method', models.CharField(blank=True, max_length=10, null=True, verbose_name='متد درخواست')),
                ('request_data', models.JSONField(blank=True, default=dict, verbose_name='داده\u200cهای درخواست')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('is_resolved', models.BooleanField(db_index=True, default=False, verbose_name='برطرف شده')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ برطرف شدن')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ خطا')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_errors', to=settings.AUTH_USER_MODEL, verbose_name='برطرف شده توسط')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ خطا',
                'verbose_name_plural': 'لاگ\u200cهای خطا',
                'db_table': 'error_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['error_type', '-created_at'], name='idx_error_type'), models.Index(fields=['is_resolved'], name='idx_resolved')],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('init', 'شروع پرداخت'), ('redirect', 'هدایت به درگاه'), ('callback', 'بازگشت از درگاه'), ('verify', 'تایید پرداخت'), ('success', 'موفق'), ('failed', 'ناموفق'), ('refund_request', 'درخواست بازگشت'), ('refunded', 'بازگشت داده شد')], db_index=True, max_length=30, verbose_name='نوع تراکنش')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ')),
                ('gateway', models.CharField(blank=True, max_length=50, null=True, verbose_name='درگاه پرداخت')),
                ('gateway_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='وضعیت درگاه')),
                ('gateway_message', models.TextField(blank=True, null=True, verbose_name='پیام درگاه')),
                ('authority', models.CharField(blank=True, max_length=100, null=True, verbose_name='Authority')),
                ('ref_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد پیگیری')),
                ('request_data', models.JSONField(blank=True, default=dict, verbose_name='داده\u200cهای درخواست')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='داده\u200cهای پاسخ')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ تراکنش')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payments.payment', verbose_name='پرداخت')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to='council.reservation', verbose_name='رزرو')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ پرداخت',
                'verbose_name_plural': 'لاگ\u200cهای پرداخت',
                'db_table': 'payment_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment', '-created_at'], name='idx_pay_log'), models.Index(fields=['transaction_type'], name='idx_trans_type'), models.Index(fields=['gateway'], name='idx_gateway_log')],
            },
        ),
        migrations.CreateModel(
            name='ReservationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=30, null=True, verbose_name='وضعیت قبلی')),
                ('new_status', models.CharField(choices=[('created', 'ایجاد شد'), ('phone_verified', 'شماره تایید شد'), ('payment_pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شد'), ('completed', 'تکمیل شد'), ('cancelled', 'لغو شد'), ('expired', 'منقضی شد')], max_length=30, verbose_name='وضعیت جدید')),
                ('change_reason', models.TextField(blank=True, null=True, verbose_name='دلیل تغییر')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات اضافی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تغییر')),
                ('changed_by', models.ForeignKey(blank=True, help_text='کاربر یا ادمینی که تغییر را ایجاد کرده', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_changes', to=settings.AUTH_USER_MODEL, verbose_name='تغییر توسط')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='council.reservation', verbose_name='رزرو')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ رزرو',
                'verbose_name_plural': 'لاگ\u200cهای رزرو',
                'db_table': 'reservation_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reservation', '-created_at'], name='idx_res_log'), models.Index(fields=['new_status'], name='idx_status_log')],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='برای کاربران مهمان (غیر لاگین)', max_length=40, null=True, verbose_name='کلید Session')),
                ('action_type', models.CharField(choices=[('registration', 'ثبت\u200cنام'), ('login', 'ورود'), ('logout', 'خروج'), ('otp_request', 'درخواست کد OTP'), ('otp_verify', 'تایید کد OTP'), ('reservation_start', 'شروع رزرو'), ('reservation_created', 'ایجاد رزرو'), ('reservation_cancelled', 'لغو رزرو'), ('payment_init', 'شروع پرداخت'), ('payment_success', 'پرداخت موفق'), ('payment_failed', 'پرداخت ناموفق'), ('profile_update', 'بروزرسانی پروفایل'), ('file_upload', 'آپلود فایل'), ('pdf_download', 'دانلود PDF'), ('page_view', 'بازدید صفحه'), ('error', 'خطا'), ('other', 'سایر')], db_index=True, max_length=50, verbose_name='نوع عملیات')),
                ('severity', models.CharField(choices=[('info', 'اطلاعاتی'), ('warning', 'هشدار'), ('error', 'خطا'), ('critical', 'بحرانی')], db_index=True, default='info', max_length=20, verbose_name='سطح اهمیت')),
                ('description', models.TextField(help_text='شرح کامل عملیات انجام شده', verbose_name='توضیحات')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه شیء')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='داده\u200cهای اضافی به صورت JSON', verbose_name='اطلاعات اضافی')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('user_agent', models.TextField(blank=True, help_text='مرورگر و سیستم عامل کاربر', null=True, verbose_name='User Agent')),
                ('device_type', models.CharField(blank=True, help_text='موبایل، تبلت، دسکتاپ', max_length=20, null=True, verbose_name='نوع دستگاه')),
                ('browser', models.CharField(blank=True, max_length=50, null=True, verbose_name='مرورگر')),
                ('os', models.CharField(blank=True, max_length=50, null=True, verbose_name='سیستم عامل')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع محتوا')),
                ('user', models.ForeignKey(blank=True, help_text='کاربری که این عملیات را انجام داده', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'فعالیت کاربر',
                'verbose_name_plural': 'فعالیت\u200cهای کاربران',
                'db_table': 'user_activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_user_activity'), models.Index(fields=['action_type', '-created_at'], name='idx_action_time'), models.Index(fields=['severity'], name='idx_severity'), models.Index(fields=['session_key'], name='idx_session'), models.Index(fields=['ip_address'], name='idx_ip')],
            },
        ),
    ]
