# Generated by Django 5.2.8 on 2025-12-08 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0002_consultationtopic_alter_servicetype_options_and_more'),
        ('logs', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paymentlog',
            name='idx_gateway_log',
        ),
        migrations.RemoveField(
            model_name='paymentlog',
            name='gateway',
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='gateway_name',
            field=models.CharField(default='zarinpal', max_length=50, verbose_name='نام درگاه'),
        ),
        migrations.AddIndex(
            model_name='paymentlog',
            index=models.Index(fields=['gateway_name'], name='idx_gateway_name'),
        ),
    ]
