# Generated by Django 5.2.8 on 2025-12-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_remove_paymentlog_idx_gateway_log_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='error_type',
            field=models.CharField(choices=[('validation', 'خطای اعتبارسنجی'), ('database', 'خطای دیتابیس'), ('payment', 'خطای پرداخت'), ('api', 'خطای API'), ('server', 'خطای سرور'), ('other', 'سایر')], max_length=30, verbose_name='نوع خطا'),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name='برطرف شده'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تراکنش'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='transaction_type',
            field=models.CharField(choices=[('init', 'شروع پرداخت'), ('redirect', 'هدایت به درگاه'), ('callback', 'بازگشت از درگاه'), ('verify', 'تایید پرداخت'), ('success', 'موفق'), ('failed', 'ناموفق'), ('refund_request', 'درخواست بازگشت'), ('refunded', 'بازگشت داده شد')], max_length=30, verbose_name='نوع تراکنش'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action_type',
            field=models.CharField(choices=[('registration', 'ثبت\u200cنام'), ('login', 'ورود'), ('logout', 'خروج'), ('otp_request', 'درخواست کد OTP'), ('otp_verify', 'تایید کد OTP'), ('reservation_start', 'شروع رزرو'), ('reservation_created', 'ایجاد رزرو'), ('reservation_cancelled', 'لغو رزرو'), ('payment_init', 'شروع پرداخت'), ('payment_success', 'پرداخت موفق'), ('payment_failed', 'پرداخت ناموفق'), ('profile_update', 'بروزرسانی پروفایل'), ('file_upload', 'آپلود فایل'), ('pdf_download', 'دانلود PDF'), ('page_view', 'بازدید صفحه'), ('error', 'خطا'), ('other', 'سایر')], max_length=50, verbose_name='نوع عملیات'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='session_key',
            field=models.CharField(blank=True, help_text='برای کاربران مهمان (غیر لاگین)', max_length=40, null=True, verbose_name='کلید Session'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='severity',
            field=models.CharField(choices=[('info', 'اطلاعاتی'), ('warning', 'هشدار'), ('error', 'خطا'), ('critical', 'بحرانی')], default='info', max_length=20, verbose_name='سطح اهمیت'),
        ),
    ]
